name: hope-env
channels:
  - conda-forge
  - pytorch
  - bottler
  - defaults
  - pytorch3d
  - nvidia
dependencies:
  - python=3.8
  - pip
  - git
  - pillow
  - gcc
  - gxx
  - boost
  - tqdm
  - easydict
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - multiprocess
  - nvidiacub
  - pytorch3d
  - pip:
    - tensorboardX
    - open3d
    - opencv-python==4.3.0.36
    - opencv-contrib-python~=4.3.0.36
    - Ninja
    - ninja==1.10.0.post2
    - omegaconf
    - pyrender
    - trimesh
    - python-fcl
    - loguru
    - pyglet
    - PyYAML
    - scenepic
    - smplx==0.1.26
    - mano
    - torchgeometry==0.1.2
    - git+https://github.com/otaheri/chamfer_distance.git
    - git+https://github.com/otaheri/MANO.git
    - git+https://github.com/otaheri/bps_torch.git
    - git+https://github.com/MPI-IS/mesh.git
    - git+https://github.com/hassony2/chumpy.git
