name: hope-env
channels:
  - conda-forge
  # - pytorch
dependencies:
  - python=3.8.11
  - pip
  - pip:
    - opencv-python
  - matplotlib
  - jupyterlab
  - easydict
  - tqdm
  - setuptools
  - cython
  - nvidia::cudatoolkit=11.1
  - numpy
  - pillow
  - pytorch::pytorch=1.9.1
  - bottler::nvidiacub
  - pytorch::torchaudio=0.9.1
  - pytorch::torchvision=0.10.1

  # - cudatoolkit=10.2
  # - cudnn=7.6
  # - pytorch 
  # - torchvision 
  # - tensorboard
