name: hope-env
channels:
  - conda-forge
  # - pytorch
dependencies:
  - python=3.8
  - pip
  - pip:
    - opencv-python
  - matplotlib
  - jupyterlab
  - easydict
  - tqdm
  # - cudatoolkit=10.2
  # - cudnn=7.6
  # - pytorch 
  # - torchvision 
  # - tensorboard
